export const FETCH_SHOPIFY_API = 'shopify/FETCH_SHOPIFY_API';
export const FETCH_SHOPIFY_API_SUCCESS =  'shopify/FETCH_SHOPIFY_API_SUCCESS';
export const FETCH_SHOPIFY_API_FAIL = 'shopify/FETCH_SHOPIFY_API_FAIL';
